name: Auto Review

on:
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    if: github.event.comment.user.login == 'k-kinzal'
    steps:
      - uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION.AUTO_REVIEW: true
          CONFIG.MODEL: gpt-4o-2024-05-13